# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'


variables:
  dockerId: sampensiontest  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: demo_api  # Replace with the name of the image you want to publish
  dockerUsername: SampensionTest

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Build docker container
    docker build -t $(dockerId).azurecr.io/demo_api -f docker/app/Dockerfile .
    docker login -u$(dockerUsername) -p$(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/demo_api:latest
  displayName: 'Build and push docker container'
  env:
    pswd: $(dockerPassword)


